spring.datasource.name=employeedb
spring.datasource.url=jdbc:mysql://localhost:3306/employeedb?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Syansoft
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


#Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shubhbhardwaj040@gmail.com
spring.mail.password=xgagntpqnsmjbdrl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
